language: php

php:
 - 5.3

before_script:
 - mysql -e 'create database magento_travis;'
 - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
 - ./.travisload.sh
 - mkdir -p build/logs
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar selfupdate
 - php composer.phar install --dev

script:
 - php vendor/bin/phpunit -c .phpunit.dist.xml

after_script:
 - php vendor/bin/coveralls

notifications:
  email: martin.aarhof@gmail.com